php m2

diff --git a/images/php-fpm/Dockerfile b/images/php-fpm/Dockerfile
--- a/images/php-fpm/Dockerfile
+++ b/images/php-fpm/Dockerfile
@@ -35,39 +35,36 @@ COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
 COPY --from=composer:1 /usr/bin/composer /usr/bin/composer1
 COPY --from=composer:2 /usr/bin/composer /usr/bin/composer2
 
-# RUN set -eux; \
-# 	cd /usr/local/etc/; \
-# 	{ \
-# 		echo '[global]'; \
-# 		echo 'error_log = /proc/self/fd/2'; \
-# 		echo; \
-# 		echo '[www]'; \
-# 		echo '; if we send this to /proc/self/fd/1, it never appears'; \
-# 		echo 'access.log = /proc/self/fd/2'; \
-# 		echo; \
-# 		echo 'clear_env = no'; \
-# 		echo; \
-# 		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
-# 		echo 'catch_workers_output = yes'; \
-# 	} | tee php-fpm.d/docker.conf; \
-# 	{ \
-# 		echo '[global]'; \
-# 		echo 'daemonize = no'; \
-# 		echo; \
-# 		echo '[www]'; \
-# 		echo 'listen = 9000'; \
-# 	} | tee php-fpm.d/zz-docker.conf; \
-#     perl -pi -e 's/^(pid|error_log|daemonize)/;$1/g' php-fpm.conf; \
-#     perl -pi -e 's/^(listen)/;$1/g' php-fpm.d/www.conf; \
-#     perl -pi -e 's/^(php_admin_(value|flag))/;$1/g' php-fpm.d/www.conf
+RUN set -eux; \
+	cd /usr/local/etc/; \
+	{ \
+		echo '[global]'; \
+		echo 'error_log = /proc/self/fd/2'; \
+		echo; \
+		echo '[www]'; \
+		echo '; if we send this to /proc/self/fd/1, it never appears'; \
+		echo 'access.log = /proc/self/fd/2'; \
+		echo; \
+		echo 'clear_env = no'; \
+		echo; \
+		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+		echo 'catch_workers_output = yes'; \
+	} | tee php-fpm.d/docker.conf; \
+	{ \
+		echo '[global]'; \
+		echo 'daemonize = no'; \
+		echo; \
+		echo '[www]'; \
+		echo 'listen = 9000'; \
+	} | tee php-fpm.d/zz-docker.conf; \
+    perl -pi -e 's/^(pid|error_log|daemonize)/;$1/g' php-fpm.conf; \
+    perl -pi -e 's/^(listen)/;$1/g' php-fpm.d/www.conf; \
+    perl -pi -e 's/^(php_admin_(value|flag))/;$1/g' php-fpm.d/www.conf
 
 
-# # Override stop signal to stop process gracefully
-# # https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163
-# STOPSIGNAL SIGQUIT
-
-
-
+# Override stop signal to stop process gracefully
+# https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163
+STOPSIGNAL SIGQUIT
 
 ## Warden
 RUN apt update
